version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:772693223288:task-definition/course-service-task:3"
        LoadBalancerInfo:
          ContainerName: "course-service"
          ContainerPort: 8080
